- name: Create the user "{{ user }}"
  user:
    name: "{{ user }}"
    state: present
    createhome: yes

- name: Add "{{ user }}" to the sudoers group
  lineinfile:
    create: yes
    path: /etc/sudoers.d/"{{ user }}"_nopasswd
    line: '"{{ user }}" ALL=(ALL) NOPASSWD:ALL'
    mode: 0440

- name: Add ssh key for user "{{ user }}"
  authorized_key:
    user: "{{ user }}"
    key: "{{ key }}"
